### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by Shihang-Wang-58** [grzsko/ASAP#3]
Hi, 
I am very interested in the features of ASAP, so I tried to run it, but an error was bothering me. After I have fully configured the environment, I run "sh run main ai" in my command line, but the command line prompts me with "OSError: [Errno 98] Address already in use". I don't know how to solve this problem. Could you provide some helps or tips? 

Or could you tell me how to more easily run the file named "Assessment of regression results. ipynb"  to reproduce the results?

Thank you very much!

**Comment by Shihang-Wang-58** [comment]
```
(py3.10) bailab@hp-HP-Z8-G4:~/software/wangshh/ASAP-main$ sh run main ai
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Restored variables from /home/bailab/software/wangshh/ASAP-main/scorers/scscore/models/full_reaxys_model_1024bool/model.ckpt-10654.as_numpy.pickle
Loading syba scorer. It's gonna take ~2 minutes.

NoneType: None
Traceback (most recent call last):
  File "/home/bailab/software/anaconda3/envs/aizynth-env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bailab/software/anaconda3/envs/aizynth-env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bailab/software/wangshh/ASAP-main/ai/main.py", line 170, in <module>
    asyncio.run(main())
  File "/home/bailab/software/anaconda3/envs/aizynth-env/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/bailab/software/anaconda3/envs/aizynth-env/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/bailab/software/wangshh/ASAP-main/ai/main.py", line 129, in main
    async with conda_app as (_, fetch_sync):
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 219, in __aenter__
    await self.start()
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 215, in start
    time, _ = await Timer.acalc(self._start())
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 43, in acalc
    result = await awaitable
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 206, in _start
    await self.fetch(None)
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 179, in fetch
    return self._process_fetch(
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 163, in _process_fetch
    raise v
http.client.BadStatusLine:
Traceback (most recent call last):
  File "/home/bailab/software/anaconda3/envs/py3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bailab/software/anaconda3/envs/py3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bailab/software/wangshh/ASAP-main/main/main.py", line 65, in <module>
    run(method())
  File "/home/bailab/software/anaconda3/envs/py3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/bailab/software/anaconda3/envs/py3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bailab/software/wangshh/ASAP-main/main/main.py", line 23, in ai
    async with app_ai() as (fetch, _):
  File "/home/bailab/software/anaconda3/envs/py3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/bailab/software/wangshh/ASAP-main/main/helpers.py", line 34, in app_ai
    async with CondaApp[AiInput, Timed[AiTree]](8001, "ai", "aizynth-env") as x:
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 219, in __aenter__
    await self.start()
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 215, in start
    time, _ = await Timer.acalc(self._start())
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 43, in acalc
    result = await awaitable
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 206, in _start
    await self.fetch(None)
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 185, in fetch
    raise AppKilled()
shared.AppKilled
(py3.10) bailab@hp-HP-Z8-G4:~/software/wangshh/ASAP-main$ Traceback (most recent call last):
  File "/home/bailab/software/anaconda3/envs/scorers/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bailab/software/anaconda3/envs/scorers/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bailab/software/wangshh/ASAP-main/scorers/main.py", line 114, in <module>
    serve(scorer)
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 86, in serve
    _serve(int(sys.argv[1]), callback)
  File "/home/bailab/software/wangshh/ASAP-main/shared.py", line 81, in _serve
    httpd = ThreadedHTTPServer(("localhost", port), S)
  File "/home/bailab/software/anaconda3/envs/scorers/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/bailab/software/anaconda3/envs/scorers/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/bailab/software/anaconda3/envs/scorers/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```
